name: merchant_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^8.0.2
  injectable: ^2.5.0 
  dio: ^5.7.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  fvm: 2.4.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  dio_cookie_manager: ^3.1.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  qr_flutter: ^4.1.0
  intl: 0.19.0
  flutter_localization: ^0.3.0
  intl_translation: ^0.20.1
  share_plus: ^10.1.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/flash.png
    - assets/images/desu.png
    - assets/images/banner.png
    - assets/images/home.png
    - assets/images/cart.png
    - assets/images/refund.png
    - assets/images/transaction_history.png
    - assets/images/person.png
    - assets/images/star.png
    - assets/images/ic_launcher.png
    - lib/l10n/
    - assets/images/appBar.png
    